language: node_js
node_js:
  - '0.10'
script: 'npm test'
# before_script:
#   - curl https://gist.githubusercontent.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
addons:
  sauce_connect: true

env:
  global:
  - secure: H3bYbatZTYinsqRc7RUs9aHvJYVBYh4t9x8K3dkCngMo2ZZayPCBBQVVpbrdX2deEdi0ZvrF+PfUd/Stf7EqsMoYhVMAVfJXG526yEuGJ/93cmA79JYVmijHcUFkYNY1VtD7NFJIjSkbqtyfOGdh/ge0acJ9daBAGfi3suQWMDQ=
  - secure: G3ejGIM0RJqWkG6pb9b1/HqA6Xs8ySsUBt23ggK+IvatvVh4tdvc0K/fyc8lY12vN8772Jd+59HPl3+RMcQmWl4kKKqBsIx0EPhZKs2/aQsYwQgud/m1s0a8XATIil1cuH+7voEQnBKTOKCvRPmLlZOvx/xMZkQcUA+wg5grPcE=
